version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.23.0
    hostname: "prometheus"
    container_name: prometheus
    ports:
      - ${PROMETHEUS_PORT}:9090
    restart: always
    volumes:
      - ./prometheus/data:/prometheus
      - ./prometheus/conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules:/opt/rules
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--storage.tsdb.retention=168h"
      - "--web.enable-lifecycle"
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"
  grafana:
    image: grafana/grafana:7.3.0
    hostname: "grafana"
    container_name: grafana
    restart: always
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - ./grafana/conf/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/data:/var/lib/grafana
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"
  alertmanager:
    image: prom/alertmanager:v0.21.0
    hostname: "alertmanager"
    container_name: alertmanager
    restart: always
    ports:
      - ${ALERTMANAGER_PORT}:9093
    volumes:
      - ./alertmanager/conf/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ./alertmanager/data:/alertmanager
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"
  consul:
    image: consul:1.9.0
    hostname: "consul"
    container_name: consul
    restart: always
    ports:
      - ${CONSUL_PORT}:8500
    volumes:
      - ./consul/data:/consul/data
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"

