global:
  [ resolve_timeout: <duration> | default = 5m ]
    [ smtp_from: <tmpl_string> ]
    [ smtp_smarthost: <string> ]
    [ smtp_hello: <string> | default = "localhost" ]
    [ smtp_auth_username: <string> ]
    [ smtp_auth_password: <secret> ]
    [ smtp_auth_identity: <string> ]
    [ smtp_auth_secret: <secret> ]
    [ smtp_require_tls: <bool> | default = true ]
    [ slack_api_url: <secret> ]
    [ victorops_api_key: <secret> ]
    [ victorops_api_url: <string> | default = "https://alert.victorops.com/integrations/generic/20131114/alert/" ]
    [ pagerduty_url: <string> | default = "https://events.pagerduty.com/v2/enqueue" ]
    [ opsgenie_api_key: <secret> ]
    [ opsgenie_api_url: <string> | default = "https://api.opsgenie.com/" ]
    [ hipchat_api_url: <string> | default = "https://api.hipchat.com/" ]
    [ hipchat_auth_token: <secret> ]
    [ wechat_api_url: <string> | default = "https://qyapi.weixin.qq.com/cgi-bin/" ]
    [ wechat_api_secret: <secret> ]
    [ wechat_api_corp_id: <string> ]
    [ http_config: <http_config> ]

templates:
  [ - <filepath> ... ]

route: <route>

receivers:
  - <receiver> ...

inhibit_rules:
  [ - <inhibit_rule> ... ]
