apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: networkPolicy-demo
  namespace: foo
spec:
  podSelector:
    matchLabels:
      app: service-b
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: service-c
