version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.5.2
    hostname: "elasticsearch"
    container_name: elasticsearch
    volumes:
      - /etc/localtime:/etc/localtime
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
    environment:
      discovery.type: single-node
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
  kibana:
    image: kibana:7.5.2
    hostname: "kibana"
    container_name: kibana
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./kibana/data:/usr/share/kibana/data
      - /etc/localtime:/etc/localtime
    ports:
      - 5601:5601
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
  logstash:
    image: logstash:7.5.2
    hostname: "logstash"
    container_name: logstash
    volumes:
      - ./logstash/data:/usr/share/logstash/data
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - /etc/localtime:/etc/localtime
    ports:
      - 5044:5044
    restart: always
    command: " --config.reload.automatic"
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "3"
