version: '3'
services:
  redis:
    image: ecs-redis:${REDIS_VERSION}
    hostname: "ecs-redis"
    container_name: ecs-redis
    volumes:
      - ./redis-data:/data
    ports:
      - 6379:${REDIS_PORT}
    restart: always
    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
  mysql:
    image: mysql:5.7
    hostname: "ecs-mysql"
    container_name: ecs-mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mysql/config/my.cnf:/etc/mysql/my.cnf
      - ./mysql/db:/var/lib/mysql
    ports:
      - 3306:${MYSQL_PORT}
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
  nginx:
    image: nginx:1.18.0
    hostname: "ecs-nginx"
    container_name: ecs-nginx
    restart: always
    env_file: .env
    volumes:
      - ./nginx/conf:/etc/nginx
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx
    ports:
      - ${NGINX_PORT_1}:${NGINX_PORT_1_MAP}
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
