## LimitRange主要用来限制创建的pod或container占用资源的大小，如果超出限定则不允许创建
apiVersion: v1
kind: LimitRange
metadata:
  name: example
  namespace: ecs2
spec:
  ## 以下配置并不是需要全部都配置，只需根据需要选择配置方式及数值即可
  limits:
    - type: Pod
      min:
        cpu: 1
        memory: 1024Mi
      max:
        cpu: 2
        memory: 2048Mi
        # 指定容器的限定资源
    - type: Container
      # 容器没有指定CPU或内存的request时提供默认值
      defaultRequest:
        cpu: 2
        memory: 2048Mi
      # 容器没有指定limits时设置默认值
      default:
        cpu: 2
        memory: 2048Mi
      # 指定容器的CPU和内存的limit及request的最大值、最小值
      max:
        cpu: 2
        memory: 2048Mi
      min:
        cpu: 1
        memory: 1024Mi
      # 每种资源request与limits的最大比值
      maxLimitRequestRatio:
        cpu: 4
        memory: 10
       # 限制挂载卷的使用大小
    - type: PersistentVolumeClaim
      min:
        storage: 1Gi
      max:
        storage: 10Gi


