apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: view
rules:
    apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - persistenvolumeclaims
      - pods
      - replicationcontrollers
      - replicationcontrollers/scale
      - serviceaccounts
      - services
    verbs:
      - get
      - list
      - watch
