apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-conf
  namespace: ecs2-mysql-cloudtest
data:
  broker.conf: |
    brokerClusterName=DefaultCluster
    brokerName=broker-a
    brokerId=0
    deleteWhen=04
    fileReservedTime=24
    autoCreateTopicEnable=true
    brokerRole=ASYNC_MASTER
    flushDiskType=SYNC_FLUSH
    syncFlushTimeout=10000
    storePathRootDir=/opt/rocketmq/mqstore
    storePathCommitLog=/opt/rocketmq/mqstore/commitlog
    storePathConsumeQueue=/opt/rocketmq/mqstore/consumequeue
    storePathIndex=/opt/rocketmq/mqstore/index
    storeCheckpoint=/opt/rocketmq/mqstore/checkpoint
    abortFile=/opt/rocketmq/mqstore/abort
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  namespace: ecs2-mysql-cloudtest
  name: mq-namesrv
  labels:
    app: mq-namesrv
spec:
  replicas: 1
  serviceName: mq-namesrv
  selector:
    matchLabels:
      app: mq-namesrv
  template:
    metadata:
      labels:
        app: mq-namesrv
    spec:
      imagePullSecrets:
        - name: ykb
      containers:
        - image: 192.168.58.120/ecs2/rocketmq:namesrv-4.7.1
          imagePullPolicy: Always
          name: namesrv
          ports:
            - protocol: TCP
              containerPort: 9876
          env:
            - name: SERVER_JVM_XMS
              value: "2g"
            - name: SERVER_JVM_XMX
              value: "2g"
            - name: SERVER_JVM_XMN
              value: "768m"
          resources:
            requests:
              memory: 2048Mi
            limits:
              memory: 3072Mi
          readinessProbe:
            tcpSocket:
              port: 9876
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 9876
            initialDelaySeconds: 120
            periodSeconds: 10
---
kind: Service
apiVersion: v1
metadata:
  namespace: ecs2-mysql-cloudtest
  name: mq-namesrv
  labels:
    app: mq-namesrv
spec:
  ports:
    - name: rocketmq-port-9876
      protocol: TCP
      port: 9876
      targetPort: 9876
  selector:
    app: mq-namesrv
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mq-broker
  namespace: ecs2-mysql-cloudtest
  labels:
    app: mq-broker
spec:
  replicas: 1
  serviceName: mq-broker
  template:
    metadata:
      name: mq-broker
      labels:
        app: mq-broker
    spec:
      volumes:
        - name: conf
          configMap:
            name: broker-conf
            items:
              - key: broker.conf
                path: broker.conf
        - name: store
          persistentVolumeClaim:
            claimName: ecs2-rocketmq-pvc
      imagePullSecrets:
        - name: ykb
      containers:
        - name: mq-broker
          image: 192.168.58.120/ecs2/rocketmq:broker-4.7.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: conf
              # 注意：使用cm挂载时，会将整个目录覆盖掉，所以要使用独立文件来进行挂载
              mountPath: /opt/mq/mq-broker
            - name: store
              mountPath: /opt/rocketmq/mqstore
              subPath: "mqstore"
          env:
            - name: NAMESRV
              value: "mq-namesrv-0.mq-namesrv.ecs2-mysql-cloudtest:9876"
            - name: BROKER_JVM_XMS
              value: "6g"
            - name: BROKER_JVM_XMX
              value: "6g"
            - name: BROKER_JVM_XMN
              value: "2g"
            - name: BROCKER_CONF_PATH
              value: "/opt/mq/mq-broker/broker.conf"
          ports:
            - containerPort: 30911
              name: broker-port
            - containerPort: 30909
              name: broker-vip-port
          resources:
            requests:
              memory: 7168Mi
            limits:
              memory: 7168Mi
      restartPolicy: Always
  selector:
    matchLabels:
      app: mq-broker
---
kind: Service
apiVersion: v1
metadata:
  namespace: ecs2-mysql-cloudtest
  name: mq-broker
  labels:
    app: mq-broker
spec:
  ports:
    - name: rocketmq-port-30909
      protocol: TCP
      port: 10909
      targetPort: 10909
    - name: rocketmq-port-30911
      protocol: TCP
      port: 10911
      targetPort: 10911
  selector:
    app: mq-broker
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mq-console
  namespace: ecs2-mysql-cloudtest
  labels:
    app: mq-console
spec:
  replicas: 1
  serviceName: mq-console
  template:
    metadata:
      name: mq-console
      labels:
        app: mq-console
    spec:
      imagePullSecrets:
        - name: ykb
      containers:
        - name: mq-console
          image: 192.168.58.120/ecs2/rocketmq:console-4.7.1
          imagePullPolicy: IfNotPresent
          env:
            - name: NAMESRV_ADDR
              value: "mq-namesrv-0.mq-namesrv.ecs2-mysql-cloudtest:9876"
            - name: MQ_CAL_OPT
              value: " --rocketmq.config.loginRequired=true  --rocketmq.config.loginName=admin --rocketmq.config.password=admin"
          ports:
            - containerPort: 8081
              name: broker-port
          resources:
            requests:
              memory: 1024Mi
            limits:
              memory: 1536Mi
      restartPolicy: Always
  selector:
    matchLabels:
      app: mq-console
---
kind: Service
apiVersion: v1
metadata:
  namespace: ecs2-mysql-cloudtest
  name: mq-console
  labels:
    app: mq-console
spec:
  ports:
    - name: rocketmq-port-8081
      protocol: TCP
      port: 12597
      targetPort: 8081
  selector:
    app: mq-console
  type: ClusterIP
  externalIPs:
    - 192.168.58.105
