apiVersion: v1
kind: PersistentVolume
metadata:
  name: ecs2-rocketmq-store
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /ecs_logs
    server: 192.168.60.205
  mountOptions:
    - nolock
    - nfsvers=3.0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecs2-rocketmq-pvc
  namespace: ecs2-mysql-cloudtest
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  volumeMode: Filesystem
  volumeName: ecs2-rocketmq-store

